version: "3.7"

services:
  bot:
    image: seventty/xhibalbabot:5.0.1
    restart: always
    ports: 
      - 3000:3000
    expose:
      - 3000
    environment:
      #BOT_TOKEN: 123456:ABC-DEF1234ghIkl-zyx57W2v1u123ew11 <- Change it with your bot token
      NODE_ENV: production
      PORT: 3000
      LOG_LEVEL: debug
    links:
      - mongo
  mongo:
    image: mongo:4.0
    ports:
      - 27017:27017
    expose: 
      - 27017
    volumes:
      - /mongodb:/data/db
volumes:
  mongodb:
